// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZzGdEMceORKRMM0PgfEpOgT5zolxw21Q',
    appId: '1:315149487915:web:c10ab9ca860b124f907f6e',
    messagingSenderId: '315149487915',
    projectId: 'convenience-c851d',
    authDomain: 'convenience-c851d.firebaseapp.com',
    storageBucket: 'convenience-c851d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDd9A76zhcTJ4VCZon-GlZEZFXBQEk--w',
    appId: '1:315149487915:android:ba311a5eac8e84f1907f6e',
    messagingSenderId: '315149487915',
    projectId: 'convenience-c851d',
    storageBucket: 'convenience-c851d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsX-wG6edY_a9szPNMenK3tiSflErpJ_c',
    appId: '1:315149487915:ios:b5c05dca66b69b2e907f6e',
    messagingSenderId: '315149487915',
    projectId: 'convenience-c851d',
    storageBucket: 'convenience-c851d.firebasestorage.app',
    iosBundleId: 'com.example.convenienceStoreErpFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsX-wG6edY_a9szPNMenK3tiSflErpJ_c',
    appId: '1:315149487915:ios:b5c05dca66b69b2e907f6e',
    messagingSenderId: '315149487915',
    projectId: 'convenience-c851d',
    storageBucket: 'convenience-c851d.firebasestorage.app',
    iosBundleId: 'com.example.convenienceStoreErpFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZzGdEMceORKRMM0PgfEpOgT5zolxw21Q',
    appId: '1:315149487915:web:d95631e5a5c4ff96907f6e',
    messagingSenderId: '315149487915',
    projectId: 'convenience-c851d',
    authDomain: 'convenience-c851d.firebaseapp.com',
    storageBucket: 'convenience-c851d.firebasestorage.app',
  );
}
